#!url=https://raw.githubusercontent.com/caovannam2ka5/locketgoldhn/main/locketnam005
#!name=LocketGold-Hoàng-Nam-005
#!desc=Crack By Hoàng_Nam_005

[Script]
# ~ By Nam2005
# ～ Egern transfer to Shadowrocket & Surge & LanceX
revenuecat = type=http-response, pattern=^https:\/\/api\.revenuecat\.com\/.+\/(receipts$|subscribers\/[^/]+$), script-path=https://raw.githubusercontent.com/caovannam2ka5/filengaylocket/main/locketnam005.js, requires-body=true, max-size=-1, timeout=60

deleteHeader = type=http-request, pattern=^https:\/\/api\.revenuecat\.com\/.+\/(receipts|subscribers), script-path=https://raw.githubusercontent.com/caovannam2ka5/deleteHeader/main/deleteHeader.js, timeout=60

[MITM]
hostname = %APPEND% api.revenuecat.com
